import { Listing } from '@/types/listings'

// Mock veriyi Listing tipine uygun hale getir
export const listings: Listing[] = [
  // Elektronik - Telefon
  {
    id: "1",
    title: "iPhone 14 Pro Max 256GB",
    price: 45000,
    location: "İstanbul",
    description: "Apple iPhone 14 Pro Max 256GB, Uzay Siyahı, 1 yıl garantili, kutulu ve faturası mevcut.",
    category: "elektronik",
    subCategory: "telefon",
    images: ["/images/listings/iphone-14-pro-max-1.jpg", "/images/listings/1750259724125-0-WhatsApp Image 2025-06-16 at 13.51.32.jpeg"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-15",
    user: {
      id: "1",
      name: "Apple Türkiye",
      email: "info@appleturkiye.com",
    },
  },
  {
    id: "2",
    title: "Samsung Galaxy S23 Ultra",
    price: 38000,
    location: "Ankara",
    description: "Samsung Galaxy S23 Ultra 512GB, Phantom Black, 2 yıl garantili, aksesuarları ile birlikte.",
    category: "elektronik",
    subCategory: "telefon",
    images: ["/images/listings/1750259425931-0-WhatsApp Image 2025-06-16 at 17.37.59.jpeg"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-02-01",
    user: {
      id: "2",
      name: "Samsung Store",
      email: "info@samsungstore.com",
    },
  },
  {
    id: "3",
    title: "MacBook Pro M2 16 inç",
    price: 65000,
    location: "İzmir",
    description: "Apple MacBook Pro M2 Pro çip, 16GB RAM, 512GB SSD, Space Gray, 1 yıl garantili.",
    category: "elektronik",
    subCategory: "bilgisayar",
    images: ["/images/listings/macbook-air-m2.jpg", "/images/listings/1750244860830-0-WhatsApp Image 2025-06-16 at 17.37.59.jpeg"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-20",
    user: {
      id: "3",
      name: "Apple Premium Reseller",
      email: "info@applereseller.com",
    },
  },
  {
    id: "4",
    title: "Matematik Özel Ders",
    price: 200,
    location: "İstanbul",
    description: "Lise ve üniversite matematik dersleri, deneyimli öğretmen, birebir veya grup dersi.",
    category: "egitim-kurslar",
    subCategory: "akademik-kurslar",
    images: ["/images/listings/placeholder-1.jpg"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-01-10",
    user: {
      id: "4",
      name: "Matematik Öğretmeni",
      email: "matematik@egitim.com",
    },
  },
  {
    id: "5",
    title: "Fizik Kursu",
    price: 300,
    location: "Ankara",
    description: "YKS ve LGS fizik hazırlık kursu, konu anlatımı ve soru çözümü.",
    category: "egitim-kurslar",
    subCategory: "akademik-kurslar",
    images: ["/images/listings/placeholder-1.jpg"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-05",
    user: {
      id: "5",
      name: "Fizik Akademi",
      email: "fizik@akademi.com",
    },
  },
  // Ev ve Bahçe - Mobilya
  {
    id: "6",
    title: "IKEA Koltuk Takımı",
    price: 8500,
    location: "İstanbul",
    description: "IKEA koltuk takımı, 3+3+1, bej renk, 2 yıl kullanıldı, temiz durumda.",
    category: "ev-ve-bahce",
    subCategory: "mobilya",
    images: ["/images/listings/ikea-koltuk.jpg"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-01-25",
    user: {
      id: "6",
      name: "Ev Sahibi",
      email: "ev@example.com",
    },
  },
  // Spor - Ayakkabı
  {
    id: "7",
    title: "Nike Air Max 270",
    price: 1200,
    location: "İzmir",
    description: "Nike Air Max 270, 42 numara, siyah-beyaz, 6 ay kullanıldı.",
    category: "giyim",
    subCategory: "ayakkabi",
    images: ["/images/listings/nike-air-max.jpg"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-02-10",
    user: {
      id: "7",
      name: "Spor Mağazası",
      email: "spor@example.com",
    },
  },
  // Elektronik - Oyun Konsolu
  {
    id: "8",
    title: "PlayStation 5",
    price: 15000,
    location: "Ankara",
    description: "PlayStation 5, 1TB, 2 kumanda, 5 oyun ile birlikte.",
    category: "elektronik",
    subCategory: "oyun-konsolu",
    images: ["/images/listings/ps5.jpg"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-30",
    user: {
      id: "8",
      name: "Oyun Dünyası",
      email: "oyun@example.com",
    },
  },
  // Elektronik - Televizyon
  {
    id: "9",
    title: "Samsung 55\" Smart TV",
    price: 8500,
    location: "İstanbul",
    description: "Samsung 55\" 4K Smart TV, 1 yıl garantili, kutulu.",
    category: "elektronik",
    subCategory: "televizyon",
    images: ["/images/listings/samsung-tv.jpg"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-02-05",
    user: {
      id: "9",
      name: "Elektronik Mağazası",
      email: "elektronik@example.com",
    },
  },
] 