import { Listing } from '@/types/listings'

// Mock veriyi Listing tipine uygun hale getir
export const listings: Listing[] = [
  // Elektronik - Telefon
  {
    id: "1",
    title: "iPhone 14 Pro Max 256GB",
    price: 45000,
    location: "İstanbul",
    description: "Apple iPhone 14 Pro Max 256GB, Uzay Siyahı, 1 yıl garantili, kutulu ve faturası mevcut.",
    category: "elektronik",
    subCategory: "telefon",
    images: ["https://picsum.photos/seed/iphone14/500/300"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-15",
    user: {
      id: "1",
      name: "Apple Türkiye",
      email: "info@appleturkiye.com",
    },
  },
  {
    id: "2",
    title: "Samsung Galaxy S23 Ultra",
    price: 38000,
    location: "Ankara",
    description: "Samsung Galaxy S23 Ultra 512GB, Phantom Black, 2 yıl garantili, aksesuarları ile birlikte.",
    category: "elektronik",
    subCategory: "telefon",
    images: ["https://picsum.photos/seed/s23ultra/500/300"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-02-01",
    user: {
      id: "2",
      name: "Samsung Store",
      email: "info@samsungstore.com",
    },
  },
  {
    id: "3",
    title: "MacBook Pro M2 16 inç",
    price: 65000,
    location: "İzmir",
    description: "Apple MacBook Pro M2 Pro çip, 16GB RAM, 512GB SSD, Space Gray, 1 yıl garantili.",
    category: "elektronik",
    subCategory: "bilgisayar",
    images: ["https://picsum.photos/seed/macbookpro/500/300"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-20",
    user: {
      id: "3",
      name: "Apple Premium Reseller",
      email: "info@applereseller.com",
    },
  },
  {
    id: "4",
    title: "Matematik Özel Ders",
    price: 200,
    location: "İstanbul",
    description: "Lise ve üniversite matematik dersleri, deneyimli öğretmen, birebir veya grup dersi.",
    category: "egitim-kurslar",
    subCategory: "akademik-kurslar",
    images: ["https://picsum.photos/seed/matematik/500/300"],
    isPremium: false,
    premiumUntil: undefined,
    createdAt: "2024-01-10",
    user: {
      id: "4",
      name: "Matematik Öğretmeni",
      email: "matematik@egitim.com",
    },
  },
  {
    id: "5",
    title: "Fizik Kursu",
    price: 300,
    location: "Ankara",
    description: "YKS ve LGS fizik hazırlık kursu, konu anlatımı ve soru çözümü.",
    category: "egitim-kurslar",
    subCategory: "akademik-kurslar",
    images: ["https://picsum.photos/seed/fizik/500/300"],
    isPremium: true,
    premiumUntil: "2024-12-31",
    createdAt: "2024-01-05",
    user: {
      id: "5",
      name: "Fizik Akademi",
      email: "fizik@akademi.com",
    },
  },
] 