export type Subcategory = {
  id: number;
  name: string;
  slug: string;
};

export type Category = {
  id: number;
  name: string;
  icon: string;
  slug: string;
  subcategories: Subcategory[];
};

export const categories: Category[] = [
  {
    id: 1,
    name: 'Elektronik',
    icon: '📱',
    slug: 'elektronik',
    subcategories: [
      { id: 101, name: 'Telefon', slug: 'telefon' },
      { id: 102, name: 'Tablet', slug: 'tablet' },
      { id: 103, name: 'Bilgisayar', slug: 'bilgisayar' },
      { id: 104, name: 'Televizyon', slug: 'televizyon' },
      { id: 105, name: 'Kamera', slug: 'kamera' },
      { id: 106, name: 'Kulaklık', slug: 'kulaklik' },
      { id: 107, name: 'Oyun Konsolu', slug: 'oyun-konsolu' },
      { id: 108, name: 'Akıllı Saat', slug: 'akilli-saat' },
      { id: 109, name: 'Ses Sistemleri', slug: 'ses-sistemleri' },
      { id: 110, name: 'Elektronik Aksesuar', slug: 'elektronik-aksesuar' },
      { id: 111, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 2,
    name: 'Ev ve Bahçe',
    icon: '🏡',
    slug: 'ev-ve-bahce',
    subcategories: [
      { id: 201, name: 'Mobilya', slug: 'mobilya' },
      { id: 202, name: 'Ev Tekstili', slug: 'ev-tekstili' },
      { id: 203, name: 'Bahçe', slug: 'bahce' },
      { id: 204, name: 'Mutfak Gereçleri', slug: 'mutfak-gerecleri' },
      { id: 205, name: 'Dekorasyon', slug: 'dekorasyon' },
      { id: 206, name: 'Aydınlatma', slug: 'aydinlatma' },
      { id: 207, name: 'Banyo', slug: 'banyo' },
      { id: 208, name: 'Ev Aletleri', slug: 'ev-aletleri' },
      { id: 209, name: 'Beyaz Eşya', slug: 'beyaz-esya' },
      { id: 210, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 3,
    name: 'Hobi & Sanat',
    icon: '🎨',
    slug: 'hobi-sanat',
    subcategories: [
      { id: 301, name: 'Müzik Aletleri', slug: 'muzik-aletleri' },
      { id: 302, name: 'Sanat Malzemeleri', slug: 'sanat-malzemeleri' },
      { id: 303, name: 'Koleksiyon', slug: 'koleksiyon' },
      { id: 304, name: 'El İşi', slug: 'el-isi' },
      { id: 305, name: 'Fotoğrafçılık', slug: 'fotografcilik' },
      { id: 306, name: 'Bahçe & Bitki', slug: 'bahce-bitki' },
      { id: 307, name: 'Balıkçılık', slug: 'balikcilik' },
      { id: 308, name: 'Spor Malzemeleri', slug: 'spor-malzemeleri' },
      { id: 309, name: 'Yazı & Kaligrafi', slug: 'yazi-kaligrafi' },
      { id: 310, name: 'Dekoratif Sanatlar', slug: 'dekoratif-sanatlar' },
      { id: 311, name: 'Takı Tasarımı', slug: 'taki-tasarimi' },
      { id: 312, name: 'Ahşap İşleri', slug: 'ahsap-isleri' },
      { id: 313, name: 'Seramik & Çömlek', slug: 'seramik-comlek' },
      { id: 314, name: 'Dikiş & Nakış', slug: 'dikis-nakis' },
      { id: 315, name: 'Maket & Model', slug: 'maket-model' },
      { id: 316, name: 'Oyun & Bulmaca', slug: 'oyun-bulmaca' },
      { id: 317, name: 'Kitap & Dergi', slug: 'kitap-dergi' },
      { id: 318, name: 'Film & Müzik', slug: 'film-muzik' },
      { id: 319, name: 'Sahne Sanatları', slug: 'sahne-sanatlari' },
      { id: 320, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 4,
    name: 'Turizm & Konaklama',
    icon: '🏨',
    slug: 'turizm-konaklama',
    subcategories: [
      { id: 401, name: 'Otel', slug: 'otel' },
      { id: 402, name: 'Apart', slug: 'apart' },
      { id: 403, name: 'Pansiyon', slug: 'pansiyon' },
      { id: 404, name: 'Villa', slug: 'villa' },
      { id: 405, name: 'Kamp Alanı', slug: 'kamp-alani' },
      { id: 406, name: 'Butik Otel', slug: 'butik-otel' },
      { id: 407, name: 'Termal Tesis', slug: 'termal-tesis' },
      { id: 408, name: 'Dağ Evi', slug: 'dag-evi' },
      { id: 409, name: 'Günlük Kiralık', slug: 'gunluk-kiralik' },
      { id: 410, name: 'Yazlık', slug: 'yazlik' },
      { id: 411, name: 'Kışlık', slug: 'kislik' },
      { id: 412, name: 'Çiftlik Evi', slug: 'ciftlik-evi' },
      { id: 413, name: 'Yat & Tekne', slug: 'yat-tekne' },
      { id: 414, name: 'Hostel', slug: 'hostel' },
      { id: 415, name: 'Motel', slug: 'motel' },
      { id: 416, name: 'Tatil Köyü', slug: 'tatil-koyu' },
      { id: 417, name: 'Sahil Evi', slug: 'sahil-evi' },
      { id: 418, name: 'Göl Kenarı', slug: 'gol-kenari' },
      { id: 419, name: 'Orman Evi', slug: 'orman-evi' },
      { id: 420, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 5,
    name: 'Hizmetler',
    icon: '🛠️',
    slug: 'hizmetler',
    subcategories: [
      { id: 501, name: 'Temizlik', slug: 'temizlik' },
      { id: 502, name: 'Nakliyat', slug: 'nakliyat' },
      { id: 503, name: 'Tadilat', slug: 'tadilat' },
      { id: 504, name: 'Tamir', slug: 'tamir' },
      { id: 505, name: 'Özel Ders', slug: 'ozel-ders' },
      { id: 506, name: 'Güzellik & Bakım', slug: 'guzellik-bakim' },
      { id: 507, name: 'Organizasyon', slug: 'organizasyon' },
      { id: 508, name: 'Danışmanlık', slug: 'danismanlik' },
      { id: 509, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 6,
    name: 'Sağlık & Güzellik',
    icon: '💆‍♀️',
    slug: 'saglik-guzellik',
    subcategories: [
      { id: 601, name: 'Kozmetik', slug: 'kozmetik' },
      { id: 602, name: 'Parfüm', slug: 'parfum' },
      { id: 603, name: 'Cilt Bakımı', slug: 'cilt-bakimi' },
      { id: 604, name: 'Saç Bakımı', slug: 'sac-bakimi' },
      { id: 605, name: 'Makyaj', slug: 'makyaj' },
      { id: 606, name: 'Kişisel Bakım', slug: 'kisisel-bakim' },
      { id: 607, name: 'Sağlık Ürünleri', slug: 'saglik-urunleri' },
      { id: 608, name: 'Güzellik Aletleri', slug: 'guzellik-aletleri' },
      { id: 609, name: 'Güneş Ürünleri', slug: 'gunes-urunleri' },
      { id: 610, name: 'Tırnak Bakımı', slug: 'tirnak-bakimi' },
      { id: 611, name: 'Ağız Bakımı', slug: 'agiz-bakimi' },
      { id: 612, name: 'Göz Bakımı', slug: 'goz-bakimi' },
      { id: 613, name: 'Vücut Bakımı', slug: 'vucut-bakimi' },
      { id: 614, name: 'Erkek Bakım', slug: 'erkek-bakim' },
      { id: 615, name: 'Bebek Bakım', slug: 'bebek-bakim' },
      { id: 616, name: 'Doğal Ürünler', slug: 'dogal-urunler' },
      { id: 617, name: 'Organik Kozmetik', slug: 'organik-kozmetik' },
      { id: 618, name: 'Sağlıklı Yaşam', slug: 'saglikli-yasam' },
      { id: 619, name: 'Güzellik Setleri', slug: 'guzellik-setleri' },
      { id: 620, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 7,
    name: 'Eğitim & Kurslar',
    icon: '📝',
    slug: 'egitim-kurslar',
    subcategories: [
      { id: 701, name: 'Yabancı Dil', slug: 'yabanci-dil' },
      { id: 702, name: 'Müzik', slug: 'muzik' },
      { id: 703, name: 'Dans', slug: 'dans' },
      { id: 704, name: 'Spor', slug: 'spor' },
      { id: 705, name: 'Bilgisayar', slug: 'bilgisayar' },
      { id: 706, name: 'Sanat', slug: 'sanat' },
      { id: 707, name: 'Kişisel Gelişim', slug: 'kisisel-gelisim' },
      { id: 708, name: 'Sürücü Kursu', slug: 'surucu-kursu' },
      { id: 709, name: 'Akademik Dersler', slug: 'akademik-dersler' },
      { id: 710, name: 'Yazılım & Kodlama', slug: 'yazilim-kodlama' },
      { id: 711, name: 'Tasarım & Grafik', slug: 'tasarim-grafik' },
      { id: 712, name: 'Diksiyon & Hitabet', slug: 'diksiyon-hitabet' },
      { id: 713, name: 'Yemek & Mutfak', slug: 'yemek-mutfak' },
      { id: 714, name: 'El Sanatları', slug: 'el-sanatlari' },
      { id: 715, name: 'Fotoğrafçılık', slug: 'fotografcilik' },
      { id: 716, name: 'Sınav Hazırlık', slug: 'sinav-hazirlik' },
      { id: 717, name: 'Özel Ders', slug: 'ozel-ders' },
      { id: 718, name: 'Online Eğitim', slug: 'online-egitim' },
      { id: 719, name: 'Mesleki Eğitim', slug: 'mesleki-egitim' },
      { id: 720, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 8,
    name: 'Moda & Stil',
    icon: '👗',
    slug: 'moda-stil',
    subcategories: [
      { id: 801, name: 'Kadın Giyim', slug: 'kadin-giyim' },
      { id: 802, name: 'Erkek Giyim', slug: 'erkek-giyim' },
      { id: 803, name: 'Çocuk Giyim', slug: 'cocuk-giyim' },
      { id: 804, name: 'Ayakkabı', slug: 'ayakkabi' },
      { id: 805, name: 'Çanta', slug: 'canta' },
      { id: 806, name: 'Aksesuar', slug: 'aksesuar' },
      { id: 807, name: 'Takı & Mücevher', slug: 'taki-mucevher' },
      { id: 808, name: 'Gözlük', slug: 'gozluk' },
      { id: 809, name: 'Şapka & Bere', slug: 'sapka-bere' },
      { id: 810, name: 'Atkı & Eldiven', slug: 'atki-eldiven' },
      { id: 811, name: 'İç Giyim', slug: 'ic-giyim' },
      { id: 812, name: 'Plaj Giyimi', slug: 'plaj-giyimi' },
      { id: 813, name: 'Spor Giyim', slug: 'spor-giyim' },
      { id: 814, name: 'Abiye & Gece Kıyafeti', slug: 'abiye-gece-kiyafeti' },
      { id: 815, name: 'Kaban & Mont', slug: 'kaban-mont' },
      { id: 816, name: 'Triko & Kazak', slug: 'triko-kazak' },
      { id: 817, name: 'Pantolon & Tulum', slug: 'pantolon-tulum' },
      { id: 818, name: 'Etek & Elbise', slug: 'etek-elbise' },
      { id: 819, name: 'Gömlek & Bluz', slug: 'gomlek-bluz' },
      { id: 820, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 9,
    name: 'Çocuk Dünyası',
    icon: '🧸',
    slug: 'cocuk-dunyasi',
    subcategories: [
      { id: 901, name: 'Oyuncak', slug: 'oyuncak' },
      { id: 902, name: 'Bebek Giyim', slug: 'bebek-giyim' },
      { id: 903, name: 'Bebek Arabası', slug: 'bebek-arabasi' },
      { id: 904, name: 'Bebek Odası', slug: 'bebek-odasi' },
      { id: 905, name: 'Bebek Bakım', slug: 'bebek-bakim' },
      { id: 906, name: 'Çocuk Giyim', slug: 'cocuk-giyim' },
      { id: 907, name: 'Çocuk Odası', slug: 'cocuk-odasi' },
      { id: 908, name: 'Eğitici Oyuncaklar', slug: 'egitici-oyuncaklar' },
      { id: 909, name: 'Bebek Beslenme', slug: 'bebek-beslenme' },
      { id: 910, name: 'Bebek Güvenlik', slug: 'bebek-guvenlik' },
      { id: 911, name: 'Bebek Banyo', slug: 'bebek-banyo' },
      { id: 912, name: 'Bebek Uyku', slug: 'bebek-uyku' },
      { id: 913, name: 'Bebek Sağlık', slug: 'bebek-saglik' },
      { id: 914, name: 'Çocuk Ayakkabı', slug: 'cocuk-ayakkabi' },
      { id: 915, name: 'Çocuk Aksesuar', slug: 'cocuk-aksesuar' },
      { id: 916, name: 'Çocuk Spor', slug: 'cocuk-spor' },
      { id: 917, name: 'Çocuk Kitapları', slug: 'cocuk-kitaplari' },
      { id: 918, name: 'Çocuk Bisikleti', slug: 'cocuk-bisikleti' },
      { id: 919, name: 'Çocuk Müzik Aletleri', slug: 'cocuk-muzik-aletleri' },
      { id: 920, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 10,
    name: 'Catering & Ticaret',
    icon: '🍽️',
    slug: 'catering-ticaret',
    subcategories: [
      { id: 1001, name: 'Restoran', slug: 'restoran' },
      { id: 1002, name: 'Kafe', slug: 'kafe' },
      { id: 1003, name: 'Pastane', slug: 'pastane' },
      { id: 1004, name: 'Catering', slug: 'catering' },
      { id: 1005, name: 'Gıda Ürünleri', slug: 'gida-urunleri' },
      { id: 1006, name: 'Mutfak Ekipmanları', slug: 'mutfak-ekipmanlari' },
      { id: 1007, name: 'Toplu Sipariş', slug: 'toplu-siparis' },
      { id: 1008, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 11,
    name: 'İş',
    icon: '💼',
    slug: 'is',
    subcategories: [
      { id: 1101, name: 'Tam Zamanlı', slug: 'tam-zamanli' },
      { id: 1102, name: 'Yarı Zamanlı', slug: 'yari-zamanli' },
      { id: 1103, name: 'Freelance', slug: 'freelance' },
      { id: 1104, name: 'Staj', slug: 'staj' },
      { id: 1105, name: 'Geçici İş', slug: 'gecici-is' },
      { id: 1106, name: 'Yönetici', slug: 'yonetici' },
      { id: 1107, name: 'Uzman', slug: 'uzman' },
      { id: 1108, name: 'Mühendis', slug: 'muhendis' },
      { id: 1109, name: 'Teknisyen', slug: 'teknisyen' },
      { id: 1110, name: 'Operatör', slug: 'operator' },
      { id: 1111, name: 'Satış & Pazarlama', slug: 'satis-pazarlama' },
      { id: 1112, name: 'Muhasebe & Finans', slug: 'muhasebe-finans' },
      { id: 1113, name: 'İnsan Kaynakları', slug: 'insan-kaynaklari' },
      { id: 1114, name: 'Bilgi Teknolojileri', slug: 'bilgi-teknolojileri' },
      { id: 1115, name: 'Müşteri Hizmetleri', slug: 'musteri-hizmetleri' },
      { id: 1116, name: 'Üretim & İmalat', slug: 'uretim-imalat' },
      { id: 1117, name: 'Lojistik & Depo', slug: 'lojistik-depo' },
      { id: 1118, name: 'Eğitim & Öğretim', slug: 'egitim-ogretim' },
      { id: 1119, name: 'Sağlık & Bakım', slug: 'saglik-bakim' },
      { id: 1120, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 12,
    name: 'Ücretsiz Gel Al',
    icon: '🎁',
    slug: 'ucretsiz-gel-al',
    subcategories: [
      { id: 1201, name: 'Mobilya', slug: 'mobilya' },
      { id: 1202, name: 'Elektronik', slug: 'elektronik' },
      { id: 1203, name: 'Giyim', slug: 'giyim' },
      { id: 1204, name: 'Kitap', slug: 'kitap' },
      { id: 1205, name: 'Oyuncak', slug: 'oyuncak' },
      { id: 1206, name: 'Ev Eşyası', slug: 'ev-esyasi' },
      { id: 1207, name: 'Spor Ekipmanı', slug: 'spor-ekipmani' },
      { id: 1208, name: 'Diğer', slug: 'diger' },
    ],
  },
  {
    id: 13,
    name: 'Diğer',
    icon: '📦',
    slug: 'diger',
    subcategories: [
      { id: 1301, name: 'Diğer', slug: 'diger' },
    ],
  },
]; 